### ISSUE TITLE
Typescript def is on the global namespace

### ISSUE THREAD

**Issue by wrench7** [weichx/cerialize#18]
Is it possible to have the typedef modified slightly by wrapping it in a `declare module 'cerialize'`?

**Comment by weichx** [comment]
@wrench7 I'm happy to do this but I'd rather change the code to be compiled into this instead of just changing the d.ts file that is generated after compilation. I can't seem to find docs / examples of how to structure the code to reflect the desired output here, have you come across any samples I can borrow from?
