### ISSUE TITLE
Ability to add space between serialized properties

### ISSUE THREAD

**Issue by st-clair-clarke** [weichx/cerialize#19]
Hi, 
Thanks for your wonderful contribution to typescript.

Request|
Given JSON.stringify(Serialize(instance), the result is a single string without any white space. 
For readability, I was wondering if there could be an optional flag to input a space (or any charcter) between the properties.

For example,
JSON.stringify(Serialize(this.name) results in : {"title":"Tom","first":"Tavin","last":"Foo","middle":"Seymour","suffix":"","isValid":true}.

I would like to generate the following instead
{"title": "Tom", "first": "Tavin", "last": "Foo", "middle": "Seymour", "suffix": "", "isValid": true} (note the spaces after each comma and between the semicolon and and its corrresponding value..

Let me know what you think.
Thanks

**Comment by weichx** [comment]
Thanks for the suggestion, we can definitely use some custom formatting options but I think in your particular case the `JSON.stringify(src, replacer, spaces)` signature already handles this for you. If you look at the docs for that function [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) you can see that there are two additional optional arguments, a replacer and a space count. I left the output of the Serialize function unformatted on purpose so that the end user can decide how formatting should be handled. I think you want to be calling `JSON.stringify(Serialize(instance),null, 4)` to get your desired output. Does this make sense to you for your use case? Happy to address something if I've missed the mark, thanks for reaching out!

**Comment by st-clair-clarke** [comment]
Thanks. I was not aware of those paramters. They work perfectly.

Cheers
