### ISSUE TITLE
Avoiding constructor invocation

### ISSUE THREAD

**Issue by nick-jones** [weichx/cerialize#27]
I'm looking to handle a case where I have a value-object style class, and the constructor performs validation against a supplied argument. To explain with an example, say I have a class that only accepts a valid looking hex string provided to its constructor:

```TypeScript
class T1 {
    @deserialize private s : string;
    
    constructor(s : string) {
        if (s == null || !/^[A-Fa-f0-9]+$/.test(s)) {
            throw new Error('Valid hex string must be provided');
        }

        this.s = s;
    }
}
```

If I then attempt to deserialize this with:

```TypeScript
Deserialize({s: 'a3ed18c'}, T1);
```

I will get:

```
Error: Valid hex string must be provided
```

This is seemingly because the constructor is invoked with `undefined` arguments. Ideally in this case, I would like the object reconstituted, but without the constructor being invoked. One thing that I'm aware of is [Object.create](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create) can potentially be used to achieve this.

So I can successfully use the following:

```TypeScript
var i = DeserializeInto({s: 'a3ed18c'}, T1, Object.create(T1.prototype));
console.log(i, '~', i instanceof T1); // T1 { s: 'a3ed18c' } '~' true
```

.. but with more complex cases this becomes impractical (i.e. with nesting, arrays?)

So I'm wondering if there is anything else that is possible in the current implementation that I'm missing?

If there isn't, would it be something that would be considered for inclusion? Naively I'd guess that all instances of `new (<any>type)()` could be replaced with `Object.create((<any>type).prototype)` (assuming `Object.create` is actually suitable). But this would create a BC break (there could be reliance on the constructor being invoked during deserialization). An options map as an additional argument could allow people to toggle this behaviour on, avoiding this problem.

**Comment by weichx** [comment]
I understand where you're coming from the the Object.create proposal. I'm fairly certain however that that would introduce issues with the `instanceof` operator and the `.constructor` property of the created object. That would also break the way the library works unfortunately because we are storing the serialization meta data in a map that is keyed by a constructor.

In general I'm a strong believer in constructors not throwing errors. I should always be able to construct an object, whether it is valid or not is a separate concern. I would probably suggest adding a `validate()` method that you call manually at construction sites. Its a bit more verbose but error handling out of a constructor can be unpredictable since your object will still be created (and memory allocated etc) but will be in a weird state because of the exception. You can add this call in an `OnDeserialized` hook but I dont think you need to since you shouldn't be serializing invalid objects in the first place. 

If you feel REALLY strongly about this I'll consider adding an annotation at the class level to invoke an alternate construction function that is supplied the response json and needs to return a constructed object instance.

**Comment by nick-jones** [comment]
Thanks for the reply!

Unfortunately I'm not completely well versed in JS, thus my rather jittery explanation. But what generally gave me confidence to suggest the `Object.create` route was I went ahead and replaced all instances of `new (<any>type)()` with `Object.create((<any>type).prototype)` and ran the tests. They pass OK. I've just run a crude test where I `console.log(keyName)` in `MetaData.constructor`, and I can't see any difference in the output between `new` vs. `Object.create`. Any ideas if I am missing something here?

Thanks for the explanation of the behaviour when throwing from the constructor.. I think I'll dive into that a bit more. If it's generally ill advised with JS due to those issues described, then I'll probably run with another approach.

**Comment by weichx** [comment]
I could be wrong and the object.create could be better, haven't tried it in quite some time. I tend to prefer `new` in general, may be a personal bias. Regardless, I do think you're better off not throwing exceptions in constructors in any language, not just JS. There may be legit use cases for wanting to do that, but generally if you need to validate input before creating an object, I'd use a factory class to do the validation + construction then return your object. That way you can keep construction separate from validation and can destroy the constructed object if it isn't valid, run alternate validators based on input, return a subclass or do whatever you want to do with it while keeping the logic abstracted away from the calling code.

**Comment by weichx** [comment]
I'm going to close, you still think this is an issue we can reopen and discuss what to do about it

**Comment by varunshoor** [comment]
@nick-jones I have been trying to get your email but apparently you don't exist on the internet except for on Github. I am really sorry that I have to resort to commenting on this thread but I really would like to talk. Can you please either DM me your email at @varunshoor or contact me at varun.shoor@kayako.com? Thanks!
