### ISSUE TITLE
Can not deserialize Generic class 

### ISSUE THREAD

**Issue by SnezanaDichevska** [weichx/cerialize#35]
I tried using GenericDeserialize and Deserialize method in order to deserialize my generic typescript class, but it  doesn't recognize any generic classes.
**Example:**
generic class:
`export class PaginatedList<T> {`
       ` @deserializeAs(T) items:T[];`
       ` @deserialize currentPage:number;`
      ` @deserialize totalCount:number;`
`}`
use: 
` Deserialize(res, PaginatedList<User>); `

Anything i'm missing here or it's simply not supported?

**Comment by weichx** [comment]
I think what you are trying to do isn't supported due to a typescript limitation. The deserialization in this library works by grabbing property definitions off of the class argument. In this case, `T` isn't a real class so `deserializeAs` doesn't know what to do with it (because it not an actual class object at runtime). 

`GenericDeserialize` is just a small casting wrapper around `Deserialize`. Normally `Deserialize` returns an `any` which you then need to cast to something usable (if you want type checking). `GenericDeserialize` just infers the type returned by using the input class argument. Here is the implementation:

```typescript
export function GenericDeserialize<T>(json : any, type : new () => T) : T {
    return <T>Deserialize(json, type);
}
```

Make sense?

**Comment by weichx** [comment]
@SnezanaDichevska this still an issue? I'll close it if I dont' hear back from you in a couple days
