### ISSUE TITLE
Naming Convention between GenericDeserialize and Deserialize

### ISSUE THREAD

**Issue by rightisleft** [weichx/cerialize#50]
I just re read the documentation and realize that i've been inverting GenericDeserialize and Deserialize.

GenericDeserialize is actually Typesafe. 

Deserialize is not type safe.

While GenericDeserialize makes sense in terms of using 'Generics' - in this context i actually associated _Generic_ to mean JSON, or Untyped. 

Maybe consider renaming to TypedDeserialize or something similar.

**Comment by weichx** [comment]
I can see where that could be mixed up, I'd like to restructure things a
bit in the next version, that's one of them

On Mar 15, 2017 6:54 PM, "Jack Murphy" <notifications@github.com> wrote:

I just re read the documentation and realize that i've been inverting
GenericDeserialize and Deserialize.

GenericDeserialize is actually Typesafe.

Deserialize is not type safe.

While GenericDeserialize makes sense in terms of using 'Generics' - in this
context i actually associated *Generic* to mean JSON, or Untyped.

Maybe consider renaming to TypedDeserialize or something similar.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/weichx/cerialize/issues/50>, or mute the thread

**Comment by StefH** [comment]
Why not define just **one single** function ?

```ts
export function Deserialize<T>(json: any) : T {
 // code here...
}
```

This function can be called like:
`const obj: any = Deserialize();`

But also:
`const address: Address = Deserialize<Address>();`

**Comment by weichx** [comment]
The reason is historical, this library was written before typescript had generics and now I don't want to break everyone's code by changing the behavior
