### ISSUE TITLE
Typed Arrays

### ISSUE THREAD

**Issue by rightisleft** [weichx/cerialize#60]
I thought i remember this working. My goal is to deserialize a top level array. 

`        
let items: TopicDTO[] = GenericDeserialize<TopicDTO[]>(action.payload, TopicDTO);
`

This is throwing:
```
Error:(41, 13) TS2322:Type 'TopicDTO' is not assignable to type 'TopicDTO[]'.
  Property 'includes' is missing in type 'TopicDTO'.
```

Is there a way to properly deserialize a top level json array into new class instances?

**Comment by weichx** [comment]
This doesn't work because the types don't match. Unfortunately this is a typescript issue and not a library issue. The 2nd argument to that function needs a concrete type (that you've passed correctly) but the generic type must match it, which isn't possible because SomeType[] is not a concrete type.

**Comment by rightisleft** [comment]
can you can overload the function to return both incarnations?

**Comment by weichx** [comment]
You mean have the signature look like this? `GenericDeserialize<T|T[]>(data : any, type : typeof T) : T|T[]`?

I'm not sure that works with type inference though the new version of TS may fix that
